### ISSUE TITLE
启动器没有找到你的软件

### ISSUE THREAD

**Issue by sonichy** [denjay/remote#2]
install.sh里面好像没有生成desktop的代码，可以这样写desktop.sh：
s="[Desktop Entry]\nName=远程助手\nComment=远程助手\nExec=`pwd`/remote.py\nIcon=`pwd`/static/img/logo.png\nPath=`pwd`\nType=Application\nCategories=System;"
echo -e $s > DJRemote.desktop
cp `pwd`/DJRemote.desktop ~/.local/share/applications/DJRemote.desktop
还有，需要一个最小化按钮，不然一直显示在桌面上，而且你这个窗口是顶置的。
发现一个Bug，传文字到剪贴板，是递加模式，即新字符串+上次的字符串。

**Comment by denjay** [comment]
1. 你是不是用root用户运行install.sh的？产生启动器图标的代码写在python文件里面，默认是在用户目录下的 .local/share/applications/Remote.desktop，所以如果用root用户执行，可能就有问题，你可以先把软件目录里的config.pkl删掉，再用普通用户执行install.sh文件试试。
2. 已增加了最小化按钮
3. 传文字到剪贴板的bug已修复，感谢反馈！
